clone_folder: C:\dev\workspace\HEVR

environment:
  matrix:
    - qt: qt4
      platform: win32

install:
  - sh environment.sh %qt%

build_script:
  - sh build.sh %platform% all
  - cd deploy
  - rm .gitignore
  - 7z a ../HEVR-%platform%-%qt%.zip *

artifacts:
  - path: HEVR-%platform%-%qt%.zip
